### ISSUE TITLE
docs: Move to next-mdx-remote

### ISSUE THREAD

**Issue by Thisen** [pmndrs/website#86]
Hi, Jotai maintainer here.

I can see the value in collecting some Poimandres docs into a single website, however this also comes with a cost.
The current architecture results in the docs for a given repo, needs to reside here. This has a few flaws:
- We can't commit doc changes in the PR flow, meaning we need to do PRs in two repos for a change
- Docs aren't local to the package

Therefore I suggest we start using [next-mdx-remote](https://github.com/hashicorp/next-mdx-remote). This has multiple advantages, but the big one for us is that we can store mdx files in other repos. This means that docs could exist in their respective repos, while having the benefit of a single website for Poimandres libs.

**Comment by dai-shi** [comment]
It would be really nice to have doc contents (mdx files only) in each repo.
So far, I see a bad sign on DX for contributing jotai docs.

@gsimone Would this be considerable? Who should we talk to other than you?

@Thisen Would you be able to work/investigate on this after jotai v1 launch? I mean, nobody else would do it.

**Comment by Thisen** [comment]
@dai-shi, yeah I'm happy to look into this after Jotai v1. It will complement the Jotai/NextJS utils stuff very well.

**Comment by drcmda** [comment]
I agree, having docs resize at the repo would be great. This has no downsides? Like some MDX have specific components they use, grids and so on. Will that contribute to work?

**Comment by dai-shi** [comment]
To: @drcmda @SaraVieira @gsimone 

@Thisen is really motivated to work on this. Do we need any coordination? Where should we discuss about the plan? Here or in discord?

**Comment by gsimone** [comment]
mdx-remote was my first choice, couldn't get it out of the gate for time issues, but I'm 100% for it, it makes maintenance of each lib easier and lets us also support multiple versions (since we fetch from remote we can easily just use an older branch or commit to build docs from).

Also consider this https://github.com/kentcdodds/mdx-bundler
I have not done proper research but have heard good things about it

**Comment by dai-shi** [comment]
> support multiple versions

This would be super nice!

**Comment by Thisen** [comment]
@drcmda @SaraVieira @gsimone @dai-shi, as Jotai v1 is released, I will starting working on this now.

**Comment by CodyJasonBennett** [comment]
I upgraded our deps so we can work with the current API in [#113](https://github.com/pmndrs/website/pull/113/files#diff-5e5186614071390e5a8824f814c2a49cd4083adc99ada4220e546a421676ca2a).

**Comment by CodyJasonBennett** [comment]
@Thisen, any progress on this? I'm curious how maintainers will tap into the proposed structure for docs within their repositories.

**Comment by Thisen** [comment]
@CodyJasonBennett, I haven't worked on it since, we, the Jotai maintainers, decided we wanted to work on some standalone docs, since we want the docs back in the repo. I'm sorry for not updating this issue.

However the issues I ran into while working on this, was the problem you're asking and how to traverse the docs structure in a remote repo. I couldn't find any examples of this pattern, but I have a feeling that it could be solved.

**Comment by CodyJasonBennett** [comment]
@Thisen, thanks for the update. I see we will have to further the design discussion.

To start, some preliminary needs:
 - docs that work in standalone/GitHub (no weird heading/formatting in the markdown as seen in MDX)
 - configurable navigation & categories (to accommodate for flattened docs and lack of MDX metadata)
 - configurable entry point (although this can be optional with an agreed-upon structure)

Some nice-to-haves:
 - multiple versions of docs (via releases/tags found in GitHub)
 - custom homepage (such as https://jotai.pmnd.rs — this can become a trend)
 - an edit link/button for readers to contribute to the source docs (inspired by three examples)

Some concerns:
 - asset resolution (where are we sourcing them from?)
 - path resolution (these will have to be corrected according to the navigation)
 - doc fetching (how are we fetching docs while cognizant of GitHub/Vercel limits)

I hope this will serve as a start, and hopefully, we can get an agreed-upon design in place.

**Comment by Thisen** [comment]
@CodyJasonBennett, sounds great. I'm happy to work on this. I believe if we can do this, we can have the markdown docs in Jotai repo and use the common pmndrs website. What do you think @dai-shi?

**Comment by dai-shi** [comment]
My personal request is to have docs markdown files in jotai repo, and let's discuss separately how we (jotai maintainers) would want to make jotai website.

Even jotai doesn't use the common pmndrs website, this move to next-mdx-remote is still useful for me for zustand and valtio, which don't have own websites.

**Comment by CodyJasonBennett** [comment]
I took a shot at this in #204. A rough implementation, but hopefully, it reveals what work is left to do.

**Comment by CodyJasonBennett** [comment]
Got this working in #204. You can try it from https://website-git-fetch-remote-pmndrs.vercel.app.

There's some stuff to work on and talk about:
 - handling updates via Vercel/GitHub deploy hooks (Vercel doesn't have git/local storage at run-time, so ISR doesn't work OOTB)
 - redirects (previously done by pages via `utils/redirect`, doing this automatically but on the client-side since we have to specify paths upfront. We'd want to rewrite paths wherever possible for UX)
 - lib-specific components (we'd need to use [`mdx-bundler`](https://github.com/kentcdodds/mdx-bundler) if we want to pull components from other repositories, but I'd much prefer to have a unified design system for the docs, particularly for demos/sandboxes -- there's some UX stuff I want to touch upon as well)

**Comment by dai-shi** [comment]
> Got this working in #204 and threw in Valtio docs from its wiki (hosted from another repo due to formatting issues). You can try it from https://website-git-fetch-remote-pmndrs.vercel.app.

https://website-git-fetch-remote-pmndrs.vercel.app/valtio/home
This is great! Is it possible we put header comments to show the nav??

> There's some stuff to work on and talk about:

@gsimone ?

**Comment by CodyJasonBennett** [comment]
> Is it possible we put header comments to show the nav??

I'm not sure if I'm reading this clearly. You can use frontmatter with and without comments (probably commented for wikis).

In the repo Valtio is currently fetched from, I've [configured the `nav` frontmatter key](https://github.com/CodyJasonBennett/valtio/blob/main/Home.md?plain=1) to match the order docs appear on the wiki.

**Comment by dai-shi** [comment]
> In the repo where Valtio is currently fetched from, I've [configured the `nav` frontmatter key](https://github.com/CodyJasonBennett/valtio/blob/main/Home.md?plain=1) to match the order docs appear on the wiki.

Oh, I didn't notice that. Cool. So, my question is probably if we can add a title in the frontmatter.

**Comment by CodyJasonBennett** [comment]
> So, my question is probably if we can add a title in the frontmatter.

Yes, and maybe we should document this somewhere for contributors. To my knowledge these are the available options for frontmatter, all of which are optional:

```mdx
---
title?: string -- Page title that will default to the reformatted file name
description?: string -- subtitle/description text to appear below the title.
react-three-fiber has this on all pages
nav?: number -- an integer from 0, specifying a custom order for the page to appear in navigation.
categories will shift to respect this
---
```

Some notes on right-hand navigation/ToC:
 - h1 elements aren't allowed, only h2-h4. We can probably clamp headers to live in this range if we haven't already
 - all headings are visible in the side navigation, with aria props where appropriate for code-only titles
 - h2 elements are treated as a parent for h3 and h4 elements

**Comment by CodyJasonBennett** [comment]
Continuing from #212:

> Just added a tiny Source by Marcin Ignac: to the first line of code, just to make sure it's properly attributed.
> 
> In general, we should:
> 
> - find a good way to attribute the examples
> - maybe move the sandboxes to the poimandres org on codesandbox and give everyone write permissions so we don't have to make forks if we have to make changes
> 
> cc @drcmda

Maybe codesandboxes in the docs should be generated from demos in the source (see how react-spring does this with demos).

This lets us use source control and co-locate sandboxes with the docs and library.

**Comment by gsimone** [comment]
We do the same with leva and maath (boxes in the code, also used as a dev playground). I think it's a solid option, we would have some asset duplication but we can make a second effort later to deduplicate them (suzannes, textures) and put them somewhere remote we can fetch.

In an effort to keep this repo lighter, I'd propose putting the sandboxes in a third repo.

On another note, this also makes it super easy to update stuff ( we can search and replace, automate version bumps etc )

**Comment by CodyJasonBennett** [comment]
I was thinking the sandboxes would live with their respective docs, so in each lib's repository. Same with custom components, although divergent design choices can get out of hand. The docs site is pretty hidden, and although we should probably make it more visible in another repo or move to the main branch, users look to a lib's repository to contribute or for help.

For authors, my goal is to reduce the docs site to a common design system to use and build on top of (this is not a shared storybook but a common identity and set of conventions). I haven't seen much talk in this area, and it's hard to improve the UX and take creative liberties without this direction.

As it stands, everything is pretty fragmented -- there's no common interface for sandboxes/examples and no rules to constrain components and layouts. This is particularly problematic for custom components and makes features like #137 pretty hard to implement.

I stress this because docs are the first thing new users see -- it's how they onboard and how they understand the tools and ecosystems we create. Docs like React beta's, Tailwind v3's, Remix's, etc., are fun and innovative. I'd like to have the same for us and create a framework that lets us iterate towards that.

**Comment by gsimone** [comment]
The initial idea was closer to what you say, but encountered me getting a new job and losing free time last year 😂 

It sounds like a great plan!

RE: sandboxes, I see your point on having them closer to the libs, sounds great
RE: moving the repo, +1 on moving it to its own repo for discoverability ( we always get the question )

**Comment by CodyJasonBennett** [comment]
I tried out `mdx-bundler` and it doesn't parse code snippets right nor give us as much control as `next-mdx-remote`. That means we won't be able to support imported components from the docs but that's probably for the best.

The `<Demo />` component is written to where it can dynamically import from anywhere, so that won't pose as an issue. I do want to tweak this (and use it everywhere) now that sandpack is officially released, but I'll wait until we get this deployed and migrated.

The only thing keeping this PR back is update strategy. I tried ISR so it'll work OOTB, but git and the filesystem aren't available to us at run-time. Vercel deploy hooks will work regardless, but that can trigger regardless of doc changes and pile up build queues forever. I think we'll have to create an API route that filters GitHub webhooks and triggers rebuilds when necessary.

**Comment by CodyJasonBennett** [comment]
Configured some stuff on Vercel that will let us re-build docs on demand. I created an API route at [`api/update`](https://github.com/pmndrs/website/blob/fetch-remote/pages/api/update.ts) that you can send GitHub push webhooks to. It will evaluate the event and update docs if authentic and docs have actually changed.

With that out of the way, let's give this a review and see what's left to get migration across the line.

This is what configuration looks like (after merge):
![image](https://user-images.githubusercontent.com/23324155/144706600-bcb65361-2b6b-40f7-9fd3-a50caa0dc113.png)

**Comment by CodyJasonBennett** [comment]
Am I good to merge #204? It's completely backward compatible but moving docs to a separate repo will require some configuration on Vercel.

I'd like to narrow the focus to design discussion from there.

**Comment by CodyJasonBennett** [comment]
Deployed. The PR is completely backward-compatible, but you can now move docs off of this repo and tweak `data/libraries.js`.

Once docs are fully migrated, I'd like to move the docs branch to its own repo (or master) and regroup on design discussion there.

**Comment by gsimone** [comment]
Incredible work @CodyJasonBennett, you are the best 👏👏👏👏

**Comment by CodyJasonBennett** [comment]
I've experimented more with MDX 2 and ISR by fetching repositories in-memory at runtime, which will do away with the current update model:
 - https://github.com/CodyJasonBennett/docs

This is a strict upgrade all-around, but the authoring experience still struggles for doc authors in remote repositories (they don't get preview deployments). We'll have to explore our options with the Vercel CI, but that's the only withstanding issue I can find outside of the design department.

**Comment by CodyJasonBennett** [comment]
Completed with #204 and #232.
